name: Data Pipeline

permissions:
  contents: write

on:
  schedule:
    # Run once a week on Sunday at midnight 
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      task:
        description: 'Task to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - sitemap_fetcher
          - refurbedscraper
          - db_uploader
          - future_task_2

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || pip install requests pandas
        
    - name: Run sitemap fetcher
      if: ${{ github.event.inputs.task == 'sitemap_fetcher' || github.event.inputs.task == 'all' || github.event_name == 'schedule' }}
      run: |
        python github/sitemap_fetcher.py
        
    - name: Run refurbed scraper
      if: ${{ github.event.inputs.task == 'refurbedscraper' || github.event.inputs.task == 'all' || github.event_name =='schedule' }}
      run: |
        python github/refurbedscraper.py
        
    - name: Run database uploader
      if: ${{ github.event.inputs.task == 'db_uploader' || github.event.inputs.task == 'all' || github.event_name =='schedule' }}
      run: |
        python github/db_uploader.py
        
    - name: Generate weekly HTML
      run: python github/generate_weekly_html.py

        
    - name: Commit and push if changes
      run: |
        git config --global user.name 'captainlkebab'
        git config --global user.email 'samilmail00@gmail.com'
        git stash --include-untracked
        git pull origin main
        git stash pop || true 
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update data from pipeline run" && git push origin main)